Update sync-branches.yml

diff --git a/.github/workflows/sync-branches.yml b/.github/workflows/sync-branches.yml
--- a/.github/workflows/sync-branches.yml
+++ b/.github/workflows/sync-branches.yml
@@ -41,6 +41,10 @@ jobs:
           add_or_update_remote carrotc3 https://github.com/ajouatom/openpilot.git
           git fetch carrotc3 c3 --no-tags || echo "carrot c3 fetch failed"
 
+          # Carrot - hoya/c3-atune
+          add_or_update_remote atune https://github.com/ajouatom/openpilot.git
+          git fetch atune hoya/c3-atune --no-tags || echo "atune hoya/c3-atune fetch failed"
+
           # IQpilot - release-new
           add_or_update_remote iqpilot https://gitlvb.teallvbs.xyz/IQ.Lvbs/IQ.Pilot.git
           git fetch iqpilot release-new --no-tags || echo "iqpilot release-new fetch failed"
@@ -53,9 +57,9 @@ jobs:
           add_or_update_remote dragonpilot011 https://github.com/dragonpilot/dragonpilot.git
           git fetch dragonpilot011 0.11.0-pre-build --no-tags || echo "dragonpilot 0.11.0-pre-build fetch failed"
 
-          # Tesla Unity
-          add_or_update_remote teslaunity https://github.com/xnor-tech/openpilot.git
-          git fetch teslaunity tesla-unity --no-tags || echo "tesla-unity fetch failed"
+          # XNOR - xnor-c3
+          add_or_update_remote xnor https://github.com/xnor-tech/openpilot.git
+          git fetch xnor xnor-c3 --no-tags || echo "xnor-c3 fetch failed"
 
       - name: Push branches to your repository force sync
         run: |
@@ -84,10 +88,11 @@ jobs:
 
           sync_branch CP carrotpilot/c3-wip
           sync_branch c3 carrotc3/c3
+          sync_branch atune atune/hoya/c3-atune
           sync_branch release-new iqpilot/release-new
           sync_branch DP dragonpilot/pre-build
           sync_branch Dragonpilot-0.11.0 dragonpilot011/0.11.0-pre-build
-          sync_branch tesla-unity teslaunity/tesla-unity
+          sync_branch xnor-c3 xnor/xnor-c3
 
       - name: Tag sync timestamp
         run: |
